import Foundation
import Testing

struct MarketingAssetTests {
    @Test func landingPageAndReadmeReferenceLocalTokenMonitorAssets() throws {
        let rootURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()

        let landingHTML = try String(
            contentsOf: rootURL.appendingPathComponent("landing/index.html"),
            encoding: .utf8
        )
        let readme = try String(
            contentsOf: rootURL.appendingPathComponent("README.md"),
            encoding: .utf8
        )

        let expectedAssetPaths = [
            "assets/branding/token-monitor-logo.png",
            "assets/screenshots/app/dashboard.png",
            "assets/screenshots/app/claude.png",
            "assets/screenshots/app/chatgpt.png",
            "assets/screenshots/install/gatekeeper-blocked.png",
            "assets/screenshots/install/gatekeeper-privacy-security.png",
            "assets/screenshots/install/gatekeeper-open-anyway.png",
            "assets/screenshots/install/gatekeeper-admin-confirm.png"
        ]

        for assetPath in expectedAssetPaths {
            #expect(FileManager.default.fileExists(atPath: rootURL.appendingPathComponent(assetPath).path))
            #expect(landingHTML.contains(assetPath))
        }

        #expect(readme.contains("## Screenshots"))
        #expect(readme.contains("assets/screenshots/app/dashboard.png"))
        #expect(readme.contains("assets/screenshots/app/claude.png"))
        #expect(readme.contains("assets/screenshots/app/chatgpt.png"))
        #expect(readme.contains("assets/screenshots/install/gatekeeper-blocked.png"))
        #expect(readme.contains("assets/screenshots/install/gatekeeper-privacy-security.png"))
        #expect(readme.contains("assets/screenshots/install/gatekeeper-open-anyway.png"))
        #expect(readme.contains("assets/screenshots/install/gatekeeper-admin-confirm.png"))
        #expect(readme.contains("[Landing page](landing/index.html)"))
    }

    @Test func releaseMaterialsReferenceDmgInstaller() throws {
        let rootURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()

        let readme = try String(
            contentsOf: rootURL.appendingPathComponent("README.md"),
            encoding: .utf8
        )
        let landingHTML = try String(
            contentsOf: rootURL.appendingPathComponent("landing/index.html"),
            encoding: .utf8
        )
        let releaseWorkflow = try String(
            contentsOf: rootURL.appendingPathComponent(".github/workflows/release.yml"),
            encoding: .utf8
        )
        let ciWorkflow = try String(
            contentsOf: rootURL.appendingPathComponent(".github/workflows/ci.yml"),
            encoding: .utf8
        )
        let publicReleaseVerifierURL = rootURL.appendingPathComponent("scripts/verify-public-release.sh")
        let publicReleaseVerifier = try String(contentsOf: publicReleaseVerifierURL, encoding: .utf8)

        let dmgScriptURL = rootURL.appendingPathComponent("scripts/package-dmg.sh")
        let releasePackageScriptURL = rootURL.appendingPathComponent("scripts/package-release.sh")
        let releasePackageScript = try String(contentsOf: releasePackageScriptURL, encoding: .utf8)
        #expect(FileManager.default.fileExists(atPath: dmgScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: dmgScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: releasePackageScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: releasePackageScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: publicReleaseVerifierURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: publicReleaseVerifierURL.path))
        #expect(readme.contains("TokenMonitor-macOS.dmg"))
        #expect(readme.contains("Gatekeeper"))
        #expect(readme.contains("notarized"))
        #expect(readme.contains("Open Anyway"))
        #expect(readme.contains("Dennoch öffnen"))
        #expect(readme.contains("Launch at login"))
        #expect(!readme.contains("DMG vs. PKG"))
        #expect(!readme.contains("SPARKLE_PRIVATE_KEY"))
        #expect(!readme.contains("TOKEN_MONITOR_CODESIGN_IDENTITY"))
        #expect(!readme.contains("TOKEN_MONITOR_NOTARIZE"))
        #expect(landingHTML.contains("TokenMonitor-macOS.dmg"))
        #expect(landingHTML.contains("Gatekeeper"))
        #expect(landingHTML.contains("notarized"))
        #expect(landingHTML.contains("Open Anyway"))
        #expect(landingHTML.contains("Dennoch öffnen"))
        #expect(landingHTML.contains("Login Items"))
        #expect(!landingHTML.contains("Would a PKG avoid"))
        #expect(!landingHTML.contains("How do updates work?"))
        let dmgScript = try String(contentsOf: dmgScriptURL, encoding: .utf8)
        #expect(dmgScript.contains("Notarization requires a signed Developer ID build."))
        #expect(dmgScript.contains("Notarization requires a Developer ID Application identity."))
        #expect(dmgScript.contains("Developer\\ ID\\ Application:*"))
        #expect(dmgScript.contains("TOKEN_MONITOR_CODESIGN_IDENTITY"))
        #expect(dmgScript.contains("codesign --verify --strict \"$DMG_PATH\""))
        #expect(dmgScript.contains("xcrun stapler validate \"$DMG_PATH\""))
        #expect(releaseWorkflow.contains("workflow_dispatch"))
        #expect(releaseWorkflow.contains("require_developer_id"))
        #expect(releaseWorkflow.contains("TOKEN_MONITOR_REQUIRE_DEVELOPER_ID"))
        #expect(releaseWorkflow.contains("RELEASE_TAG:"))
        #expect(releaseWorkflow.contains("github.event.inputs.tag"))
        #expect(releaseWorkflow.contains("package-release.sh"))
        #expect(releaseWorkflow.contains("package_args+=(--require-distribution-ready)"))
        #expect(releaseWorkflow.contains("dist/TokenMonitor-macOS.dmg"))
        #expect(releaseWorkflow.contains("TOKEN_MONITOR_DEVELOPER_ID_CERTIFICATE_BASE64"))
        #expect(releaseWorkflow.contains("TOKEN_MONITOR_CODESIGN_IDENTITY"))
        #expect(releaseWorkflow.contains("Developer\\ ID\\ Application:*"))
        #expect(releaseWorkflow.contains("must start with 'Developer ID Application:'"))
        #expect(releaseWorkflow.contains("TOKEN_MONITOR_NOTARY_APP_PASSWORD"))
        #expect(releaseWorkflow.contains("TOKEN_MONITOR_NOTARIZE=1"))
        #expect(releaseWorkflow.contains("Developer ID signing is not configured; skipping notarization."))
        #expect(releaseWorkflow.contains("Refusing to upload a signed non-notarized release."))
        #expect(ciWorkflow.contains("Check release scripts"))
        #expect(ciWorkflow.contains("bash -n scripts/*.sh"))
        #expect(ciWorkflow.contains("./scripts/check-app-store-metadata.sh --help"))
        #expect(ciWorkflow.contains("./scripts/check-app-store-screenshots.sh --help"))
        #expect(ciWorkflow.contains("./scripts/check-app-store-identity.sh --help"))
        #expect(ciWorkflow.contains("./scripts/check-release-recovery-readiness.sh --help"))
        #expect(ciWorkflow.contains("./scripts/check-publication-legal-gates.sh --help"))
        #expect(ciWorkflow.contains("./scripts/check-app-store-metadata.sh"))
        #expect(ciWorkflow.contains("./scripts/audit-apple-distribution.sh --help"))
        #expect(ciWorkflow.contains("./scripts/package-mas-pkg.sh --help"))
        #expect(ciWorkflow.contains("./scripts/check-app-store-upload-readiness.sh --help"))
        #expect(ciWorkflow.contains("Missing TOKEN_MONITOR_MAS_CODESIGN_IDENTITY"))
        #expect(publicReleaseVerifier.contains("TokenMonitor-macOS.dmg"))
        #expect(publicReleaseVerifier.contains("TokenMonitor-macOS.zip"))
        #expect(publicReleaseVerifier.contains("appcast.xml"))
        #expect(publicReleaseVerifier.contains("TAG\" == \"-h\" || \"$TAG\" == \"--help\""))
        #expect(publicReleaseVerifier.contains("updates/$UPDATE_ZIP_NAME"))
        #expect(publicReleaseVerifier.contains("TOKEN_MONITOR_VERIFY_DMG_SIGNATURE=1"))
        #expect(publicReleaseVerifier.contains("public DMG, GitHub ZIP, and Sparkle update ZIP"))
        #expect(publicReleaseVerifier.contains("spctl --assess --type open"))
        #expect(publicReleaseVerifier.contains("xcrun stapler validate"))
        #expect(publicReleaseVerifier.contains("verify_downloaded_zip \"GitHub ZIP\""))
        #expect(publicReleaseVerifier.contains("verify_downloaded_zip \"Sparkle update ZIP\""))
        #expect(publicReleaseVerifier.contains("Downloaded $label app code signature verifies"))
        #expect(publicReleaseVerifier.contains("Downloaded $label app version matches"))
        #expect(publicReleaseVerifier.contains("dist/public-release-verification"))
        #expect(releasePackageScript.contains("--require-distribution-ready"))
        #expect(releasePackageScript.contains("TOKEN_MONITOR_REQUIRE_DISTRIBUTION_READY"))
        #expect(releasePackageScript.contains("scripts/check-apple-distribution.sh\" --require-ready"))
        #expect(releasePackageScript.contains("verify_release_zip \"GitHub release ZIP\""))
        #expect(releasePackageScript.contains("verify_release_zip \"Sparkle update ZIP\""))
        #expect(releasePackageScript.contains("did not contain TokenMonitor.app"))
        #expect(releasePackageScript.contains("version mismatch"))
        #expect(releasePackageScript.contains("Verified %s %s contains signed TokenMonitor.app"))
    }

    @Test func appleDistributionReadinessDocCoversReleasePaths() throws {
        let rootURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()

        let readme = try String(
            contentsOf: rootURL.appendingPathComponent("README.md"),
            encoding: .utf8
        )
        let distributionDocURL = rootURL.appendingPathComponent("docs/apple-distribution-readiness.md")
        let distributionDoc = try String(contentsOf: distributionDocURL, encoding: .utf8)
        let accessHandoffURL = rootURL.appendingPathComponent("docs/apple-access-handoff.md")
        let accessHandoff = try String(contentsOf: accessHandoffURL, encoding: .utf8)
        let completionAuditURL = rootURL.appendingPathComponent("docs/apple-distribution-completion-audit.md")
        let completionAudit = try String(contentsOf: completionAuditURL, encoding: .utf8)
        let credentialRunbookURL = rootURL.appendingPathComponent("docs/apple-credential-runbook.md")
        let credentialRunbook = try String(contentsOf: credentialRunbookURL, encoding: .utf8)
        let masFeasibilityURL = rootURL.appendingPathComponent("docs/mac-app-store-feasibility.md")
        let masFeasibility = try String(contentsOf: masFeasibilityURL, encoding: .utf8)
        let masEntitlementsURL = rootURL.appendingPathComponent("packaging/TokenMonitorMAS.entitlements")
        let masEntitlements = try String(contentsOf: masEntitlementsURL, encoding: .utf8)
        let appStoreIdentityURL = rootURL.appendingPathComponent("docs/app-store-connect-identity.md")
        let appStoreIdentity = try String(contentsOf: appStoreIdentityURL, encoding: .utf8)
        let releaseRecoveryRunbookURL = rootURL.appendingPathComponent("docs/release-recovery-runbook.md")
        let releaseRecoveryRunbook = try String(contentsOf: releaseRecoveryRunbookURL, encoding: .utf8)
        let legalChecklistURL = rootURL.appendingPathComponent("docs/publication-legal-checklist.md")
        let legalChecklist = try String(contentsOf: legalChecklistURL, encoding: .utf8)
        let appStorePacketURL = rootURL.appendingPathComponent("docs/app-store-submission-packet.md")
        let appStorePacket = try String(contentsOf: appStorePacketURL, encoding: .utf8)
        let appStorePrivacyLabelsURL = rootURL.appendingPathComponent("docs/app-store-privacy-labels.md")
        let appStorePrivacyLabels = try String(contentsOf: appStorePrivacyLabelsURL, encoding: .utf8)
        let appStoreScreenshotChecklistURL = rootURL.appendingPathComponent("docs/app-store-screenshot-checklist.md")
        let appStoreScreenshotChecklist = try String(contentsOf: appStoreScreenshotChecklistURL, encoding: .utf8)
        let masSmokeTestURL = rootURL.appendingPathComponent("docs/mas-sandbox-smoke-test.md")
        let masSmokeTest = try String(contentsOf: masSmokeTestURL, encoding: .utf8)
        let masSmokeTestReceiptURL = rootURL.appendingPathComponent("docs/mas-sandbox-smoke-test-receipt.md")
        let masSmokeTestReceipt = try String(contentsOf: masSmokeTestReceiptURL, encoding: .utf8)
        let readinessScriptURL = rootURL.appendingPathComponent("scripts/check-apple-distribution.sh")
        let readinessScript = try String(contentsOf: readinessScriptURL, encoding: .utf8)
        let githubSecretsScriptURL = rootURL.appendingPathComponent("scripts/check-github-release-secrets.sh")
        let githubSecretsScript = try String(contentsOf: githubSecretsScriptURL, encoding: .utf8)
        let appStoreMetadataScriptURL = rootURL.appendingPathComponent("scripts/check-app-store-metadata.sh")
        let appStoreMetadataScript = try String(contentsOf: appStoreMetadataScriptURL, encoding: .utf8)
        let appStoreScreenshotScriptURL = rootURL.appendingPathComponent("scripts/check-app-store-screenshots.sh")
        let appStoreScreenshotScript = try String(contentsOf: appStoreScreenshotScriptURL, encoding: .utf8)
        let appStoreIdentityScriptURL = rootURL.appendingPathComponent("scripts/check-app-store-identity.sh")
        let appStoreIdentityScript = try String(contentsOf: appStoreIdentityScriptURL, encoding: .utf8)
        let releaseRecoveryScriptURL = rootURL.appendingPathComponent("scripts/check-release-recovery-readiness.sh")
        let releaseRecoveryScript = try String(contentsOf: releaseRecoveryScriptURL, encoding: .utf8)
        let distributionAuditScriptURL = rootURL.appendingPathComponent("scripts/audit-apple-distribution.sh")
        let distributionAuditScript = try String(contentsOf: distributionAuditScriptURL, encoding: .utf8)
        let preflightScriptURL = rootURL.appendingPathComponent("scripts/preflight-release.sh")
        let preflightScript = try String(contentsOf: preflightScriptURL, encoding: .utf8)
        let masReadinessScriptURL = rootURL.appendingPathComponent("scripts/check-mas-readiness.sh")
        let masReadinessScript = try String(contentsOf: masReadinessScriptURL, encoding: .utf8)
        let masVerifierScriptURL = rootURL.appendingPathComponent("scripts/verify-mas-build.sh")
        let masVerifierScript = try String(contentsOf: masVerifierScriptURL, encoding: .utf8)
        let masPackageScriptURL = rootURL.appendingPathComponent("scripts/package-mas-pkg.sh")
        let masPackageScript = try String(contentsOf: masPackageScriptURL, encoding: .utf8)
        let masPreflightScriptURL = rootURL.appendingPathComponent("scripts/preflight-mas-submission.sh")
        let masPreflightScript = try String(contentsOf: masPreflightScriptURL, encoding: .utf8)
        let appStoreUploadScriptURL = rootURL.appendingPathComponent("scripts/check-app-store-upload-readiness.sh")
        let appStoreUploadScript = try String(contentsOf: appStoreUploadScriptURL, encoding: .utf8)
        let appStoreGateScriptURL = rootURL.appendingPathComponent("scripts/check-app-store-submission-gates.sh")
        let appStoreGateScript = try String(contentsOf: appStoreGateScriptURL, encoding: .utf8)
        let publicationLegalGateScriptURL = rootURL.appendingPathComponent("scripts/check-publication-legal-gates.sh")
        let publicationLegalGateScript = try String(contentsOf: publicationLegalGateScriptURL, encoding: .utf8)
        let settingsViewURL = rootURL.appendingPathComponent("Sources/TokenMonitorApp/SettingsView.swift")
        let settingsView = try String(contentsOf: settingsViewURL, encoding: .utf8)
        let appUpdateControllerURL = rootURL.appendingPathComponent("Sources/TokenMonitorApp/AppUpdateController.swift")
        let appUpdateController = try String(contentsOf: appUpdateControllerURL, encoding: .utf8)

        #expect(FileManager.default.fileExists(atPath: distributionDocURL.path))
        #expect(FileManager.default.fileExists(atPath: accessHandoffURL.path))
        #expect(FileManager.default.fileExists(atPath: completionAuditURL.path))
        #expect(FileManager.default.fileExists(atPath: credentialRunbookURL.path))
        #expect(FileManager.default.fileExists(atPath: masFeasibilityURL.path))
        #expect(FileManager.default.fileExists(atPath: masEntitlementsURL.path))
        #expect(FileManager.default.fileExists(atPath: appStoreIdentityURL.path))
        #expect(FileManager.default.fileExists(atPath: releaseRecoveryRunbookURL.path))
        #expect(FileManager.default.fileExists(atPath: legalChecklistURL.path))
        #expect(FileManager.default.fileExists(atPath: appStorePacketURL.path))
        #expect(FileManager.default.fileExists(atPath: appStorePrivacyLabelsURL.path))
        #expect(FileManager.default.fileExists(atPath: appStoreScreenshotChecklistURL.path))
        #expect(FileManager.default.fileExists(atPath: masSmokeTestURL.path))
        #expect(FileManager.default.fileExists(atPath: masSmokeTestReceiptURL.path))
        #expect(FileManager.default.fileExists(atPath: readinessScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: readinessScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: githubSecretsScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: githubSecretsScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: appStoreMetadataScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: appStoreMetadataScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: appStoreScreenshotScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: appStoreScreenshotScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: appStoreIdentityScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: appStoreIdentityScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: releaseRecoveryScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: releaseRecoveryScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: distributionAuditScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: distributionAuditScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: preflightScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: preflightScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: masReadinessScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: masReadinessScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: masVerifierScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: masVerifierScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: masPackageScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: masPackageScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: masPreflightScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: masPreflightScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: appStoreUploadScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: appStoreUploadScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: appStoreGateScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: appStoreGateScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: publicationLegalGateScriptURL.path))
        #expect(FileManager.default.isExecutableFile(atPath: publicationLegalGateScriptURL.path))
        #expect(FileManager.default.fileExists(atPath: settingsViewURL.path))
        #expect(FileManager.default.fileExists(atPath: appUpdateControllerURL.path))
        #expect(readme.contains("docs/apple-distribution-readiness.md"))
        #expect(readme.contains("docs/apple-access-handoff.md"))
        #expect(readme.contains("docs/apple-credential-runbook.md"))
        #expect(readme.contains("docs/mac-app-store-feasibility.md"))
        #expect(readme.contains("docs/app-store-submission-packet.md"))
        #expect(readme.contains("docs/app-store-connect-identity.md"))
        #expect(readme.contains("docs/app-store-privacy-labels.md"))
        #expect(readme.contains("docs/app-store-screenshot-checklist.md"))
        #expect(readme.contains("docs/release-recovery-runbook.md"))
        #expect(readme.contains("docs/publication-legal-checklist.md"))
        #expect(distributionDoc.contains("docs/apple-credential-runbook.md"))
        #expect(distributionDoc.contains("docs/apple-access-handoff.md"))
        #expect(distributionDoc.contains("docs/apple-distribution-completion-audit.md"))
        #expect(distributionDoc.contains("docs/mac-app-store-feasibility.md"))
        #expect(distributionDoc.contains("docs/app-store-submission-packet.md"))
        #expect(distributionDoc.contains("docs/app-store-connect-identity.md"))
        #expect(distributionDoc.contains("packaging/TokenMonitorMAS.entitlements"))
        #expect(distributionDoc.contains("docs/publication-legal-checklist.md"))
        #expect(distributionDoc.contains("scripts/check-apple-distribution.sh"))
        #expect(distributionDoc.contains("scripts/check-github-release-secrets.sh"))
        #expect(distributionDoc.contains("scripts/audit-apple-distribution.sh"))
        #expect(distributionDoc.contains("scripts/preflight-release.sh"))
        #expect(distributionDoc.contains("scripts/verify-public-release.sh"))
        #expect(distributionDoc.contains("scripts/check-mas-readiness.sh"))
        #expect(distributionDoc.contains("scripts/check-app-store-submission-gates.sh"))
        #expect(distributionDoc.contains("scripts/package-mas-pkg.sh"))
        #expect(distributionDoc.contains("scripts/check-app-store-upload-readiness.sh"))
        #expect(distributionDoc.contains("docs/release-recovery-runbook.md"))
        #expect(distributionDoc.contains("scripts/check-release-recovery-readiness.sh"))
        #expect(distributionDoc.contains("docs/mas-sandbox-smoke-test.md"))
        #expect(distributionDoc.contains("Developer ID DMG"))
        #expect(distributionDoc.contains("swift test` passes with 34 tests"))
        #expect(distributionDoc.contains("Mac App Store Feasibility"))
        #expect(distributionDoc.contains("TOKEN_MONITOR_CODESIGN_IDENTITY"))
        #expect(distributionDoc.contains("TOKEN_MONITOR_NOTARIZE"))
        #expect(distributionDoc.contains("TOKEN_MONITOR_DEVELOPER_ID_CERTIFICATE_BASE64"))
        #expect(distributionDoc.contains("TOKEN_MONITOR_NOTARY_APP_PASSWORD"))
        #expect(distributionDoc.contains("App Store Connect API"))
        #expect(distributionDoc.contains("SPARKLE_PRIVATE_KEY"))
        #expect(distributionDoc.contains("Marketing Setup"))
        #expect(distributionDoc.contains("Ongoing Issue-Fixing Loop"))
        #expect(distributionDoc.contains("Completion Audit"))
        #expect(distributionDoc.contains("The repository is prepared for Apple Developer access."))
        #expect(distributionDoc.contains("No Developer ID Application certificate is installed locally."))
        #expect(distributionDoc.contains("Gatekeeper rejects the current local app and DMG."))
        #expect(distributionDoc.contains("not complete until a signed, notarized, stapled Developer ID release is produced"))
        #expect(distributionDoc.contains("Repository license and final legal/privacy approvals remain human approval gates"))
        #expect(accessHandoff.contains("Do not paste Apple ID passwords"))
        #expect(accessHandoff.contains("Role Matrix"))
        #expect(accessHandoff.contains("Create Developer ID certificates"))
        #expect(accessHandoff.contains("Account Holder"))
        #expect(accessHandoff.contains("App Manager"))
        #expect(accessHandoff.contains("Revocation Checklist"))
        #expect(accessHandoff.contains("docs/apple-credential-runbook.md"))
        #expect(accessHandoff.contains("docs/app-store-connect-identity.md"))
        #expect(accessHandoff.contains("./scripts/check-app-store-identity.sh --require-ready"))
        #expect(accessHandoff.contains("./scripts/check-app-store-upload-readiness.sh --require-ready"))
        #expect(completionAudit.contains("Prompt-To-Artifact Checklist"))
        #expect(completionAudit.contains("Document Apple access handoff"))
        #expect(completionAudit.contains("Run consolidated completion audit"))
        #expect(completionAudit.contains("./scripts/audit-apple-distribution.sh --require-complete"))
        #expect(completionAudit.contains("Validate App Store metadata limits"))
        #expect(completionAudit.contains("./scripts/check-app-store-metadata.sh"))
        #expect(completionAudit.contains("Check App Store Connect identity"))
        #expect(completionAudit.contains("./scripts/check-app-store-identity.sh --require-ready"))
        #expect(completionAudit.contains("Prepare release recovery path"))
        #expect(completionAudit.contains("./scripts/check-release-recovery-readiness.sh --require-ready"))
        #expect(completionAudit.contains("Not complete."))
        #expect(completionAudit.contains("./scripts/check-github-release-secrets.sh --require-signing-secrets"))
        #expect(completionAudit.contains("enable `require_developer_id`"))
        #expect(completionAudit.contains("spctl --assess --type execute --verbose=4"))
        #expect(completionAudit.contains("Do not mark the Apple distribution objective complete"))
        #expect(completionAudit.contains("Apple Distribution certificate"))
        #expect(completionAudit.contains("Keep MAS update UI App Store-safe"))
        #expect(completionAudit.contains("Mac App Store installer distribution certificate"))
        #expect(completionAudit.contains("Mac App Store installer distribution identities separately"))
        #expect(completionAudit.contains("dist/mas/TokenMonitor-macOS-AppStore.pkg"))
        #expect(completionAudit.contains("./scripts/check-app-store-upload-readiness.sh --require-ready"))
        #expect(completionAudit.contains("./scripts/check-app-store-screenshots.sh --require-ready"))
        #expect(completionAudit.contains("Sandbox smoke test"))
        #expect(completionAudit.contains("docs/mas-sandbox-smoke-test.md"))
        #expect(completionAudit.contains("docs/mas-sandbox-smoke-test-receipt.md"))
        #expect(completionAudit.contains("./scripts/check-app-store-submission-gates.sh --require-human-gates"))
        #expect(completionAudit.contains("./scripts/check-publication-legal-gates.sh --require-legal-gates"))
        #expect(completionAudit.contains("human/App Store Connect acknowledgements"))
        #expect(completionAudit.contains("gh run list --repo MediaPublishing/token-monitor --branch main --limit 1"))
        #expect(completionAudit.contains("release script smoke checks"))
        #expect(readinessScript.contains("notarytool"))
        #expect(readinessScript.contains("stapler"))
        #expect(readinessScript.contains("Developer ID Application"))
        #expect(readinessScript.contains("Mac App Store installer distribution identity"))
        #expect(readinessScript.contains("3rd Party Mac Developer Installer|Mac Installer Distribution"))
        #expect(readinessScript.contains("Authority=Developer ID Application:"))
        #expect(readinessScript.contains("is signed with a Developer ID Application authority"))
        #expect(readinessScript.contains("is not signed with a Developer ID Application authority"))
        #expect(readinessScript.contains("DMG code signature verifies"))
        #expect(readinessScript.contains("TOKEN_MONITOR_NOTARY_PROFILE"))
        #expect(readinessScript.contains("--require-ready"))
        #expect(readinessScript.contains("TOKEN_MONITOR_REQUIRE_DISTRIBUTION_READY"))
        #expect(readinessScript.contains("Apple distribution readiness is strict-clean"))
        #expect(githubSecretsScript.contains("TOKEN_MONITOR_REQUIRE_SIGNING_SECRETS"))
        #expect(githubSecretsScript.contains("--require-signing-secrets"))
        #expect(githubSecretsScript.contains("TOKEN_MONITOR_DEVELOPER_ID_CERTIFICATE_BASE64"))
        #expect(githubSecretsScript.contains("SPARKLE_PRIVATE_KEY"))
        #expect(githubSecretsScript.contains("GitHub secret values are not readable via gh"))
        #expect(githubSecretsScript.contains("confirm names only"))
        #expect(githubSecretsScript.contains("Local TOKEN_MONITOR_CODESIGN_IDENTITY must start with 'Developer ID Application:'"))
        #expect(githubSecretsScript.contains("Release workflow validates the GitHub secret value at runtime"))
        #expect(appStoreMetadataScript.contains("App name"))
        #expect(appStoreMetadataScript.contains("Promotional text"))
        #expect(appStoreMetadataScript.contains("Keywords are"))
        #expect(appStoreMetadataScript.contains("not longer than two characters"))
        #expect(appStoreMetadataScript.contains("Privacy URL"))
        #expect(appStoreScreenshotScript.contains("--require-ready"))
        #expect(appStoreScreenshotScript.contains("TOKEN_MONITOR_APP_STORE_SCREENSHOT_DIR"))
        #expect(appStoreScreenshotScript.contains("Screenshot count must be between 1 and 10"))
        #expect(appStoreScreenshotScript.contains("1280 x 800"))
        #expect(appStoreScreenshotScript.contains("2880 x 1800"))
        #expect(appStoreScreenshotScript.contains("Manual screenshot gate"))
        #expect(appStoreIdentityScript.contains("TOKEN_MONITOR_APP_STORE_TEAM_ID"))
        #expect(appStoreIdentityScript.contains("TOKEN_MONITOR_APP_STORE_SKU"))
        #expect(appStoreIdentityScript.contains("TOKEN_MONITOR_APP_STORE_TEAM_APPROVED"))
        #expect(appStoreIdentityScript.contains("TOKEN_MONITOR_APP_STORE_BUNDLE_ID_APPROVED"))
        #expect(appStoreIdentityScript.contains("TOKEN_MONITOR_APP_STORE_SKU_APPROVED"))
        #expect(appStoreIdentityScript.contains("TOKEN_MONITOR_APP_STORE_CATEGORY_APPROVED"))
        #expect(appStoreIdentityScript.contains("TOKEN_MONITOR_APP_STORE_TEAM_ID is not set"))
        #expect(appStoreIdentityScript.contains("TOKEN_MONITOR_APP_STORE_SKU is not set"))
        #expect(appStoreIdentityScript.contains("App Store Connect identity is not ready"))
        #expect(distributionAuditScript.contains("--require-complete"))
        #expect(distributionAuditScript.contains("--run-tests"))
        #expect(distributionAuditScript.contains("without uploading, submitting"))
        #expect(distributionAuditScript.contains("Check App Store metadata limits"))
        #expect(distributionAuditScript.contains("./scripts/check-app-store-metadata.sh"))
        #expect(distributionAuditScript.contains("./scripts/check-app-store-screenshots.sh"))
        #expect(distributionAuditScript.contains("./scripts/check-app-store-screenshots.sh --require-ready"))
        #expect(distributionAuditScript.contains("./scripts/check-app-store-identity.sh"))
        #expect(distributionAuditScript.contains("./scripts/check-app-store-identity.sh --require-ready"))
        #expect(distributionAuditScript.contains("./scripts/check-github-release-secrets.sh --require-signing-secrets"))
        #expect(distributionAuditScript.contains("./scripts/check-apple-distribution.sh --require-ready"))
        #expect(distributionAuditScript.contains("./scripts/check-app-store-upload-readiness.sh --require-ready"))
        #expect(distributionAuditScript.contains("./scripts/check-app-store-submission-gates.sh --require-human-gates"))
        #expect(distributionAuditScript.contains("./scripts/check-publication-legal-gates.sh"))
        #expect(distributionAuditScript.contains("./scripts/check-publication-legal-gates.sh --require-legal-gates"))
        #expect(distributionAuditScript.contains("./scripts/check-release-recovery-readiness.sh"))
        #expect(distributionAuditScript.contains("./scripts/check-release-recovery-readiness.sh --require-ready"))
        #expect(distributionAuditScript.contains("Apple distribution is not complete yet"))
        #expect(preflightScript.contains("swift test"))
        #expect(preflightScript.contains("./scripts/verify-mas-build.sh"))
        #expect(masVerifierScript.contains("--require-apple-distribution"))
        #expect(masVerifierScript.contains("TOKEN_MONITOR_REQUIRE_APPLE_DISTRIBUTION"))
        #expect(masVerifierScript.contains("Authority=Apple Distribution:"))
        #expect(masVerifierScript.contains("MAS app is not signed with an Apple Distribution identity"))
        #expect(settingsView.contains("#if MAS_BUILD"))
        #expect(settingsView.contains("Updates are delivered by the Mac App Store."))
        #expect(settingsView.contains("Use Sparkle to watch the GitHub release feed and offer new versions."))
        #expect(settingsView.contains("Check for Updates..."))
        #expect(appUpdateController.contains("#if MAS_BUILD"))
        #expect(appUpdateController.contains("Updates are delivered by the Mac App Store for MAS builds."))
        #expect(appUpdateController.contains("import Sparkle"))
        #expect(masPackageScript.contains("TOKEN_MONITOR_MAS_INSTALLER_IDENTITY"))
        #expect(masPackageScript.contains("3rd Party Mac Developer Installer:"))
        #expect(masPackageScript.contains("Mac Installer Distribution:"))
        #expect(masPackageScript.contains("productbuild"))
        #expect(masPackageScript.contains("pkgutil --check-signature"))
        #expect(masPackageScript.contains("TokenMonitor-macOS-AppStore.pkg"))
        #expect(masPackageScript.contains("verify-mas-build.sh\" --require-apple-distribution"))
        #expect(masPreflightScript.contains("TOKEN_MONITOR_MAS_CODESIGN_IDENTITY"))
        #expect(masPreflightScript.contains("TOKEN_MONITOR_MAS_INSTALLER_IDENTITY"))
        #expect(masPreflightScript.contains("TOKEN_MONITOR_APP_STORE_TEAM_ID"))
        #expect(masPreflightScript.contains("TOKEN_MONITOR_APP_STORE_SKU"))
        #expect(masPreflightScript.contains("TOKEN_MONITOR_APP_STORE_TEAM_APPROVED=1"))
        #expect(masPreflightScript.contains("TOKEN_MONITOR_APP_STORE_BUNDLE_ID_APPROVED=1"))
        #expect(masPreflightScript.contains("TOKEN_MONITOR_APP_STORE_SKU_APPROVED=1"))
        #expect(masPreflightScript.contains("TOKEN_MONITOR_APP_STORE_CATEGORY_APPROVED=1"))
        #expect(masPreflightScript.contains("Apple Distribution:"))
        #expect(masPreflightScript.contains("Mac Installer Distribution:"))
        #expect(masPreflightScript.contains("swift test"))
        #expect(masPreflightScript.contains("./scripts/check-mas-readiness.sh"))
        #expect(masPreflightScript.contains("./scripts/check-app-store-identity.sh --require-ready"))
        #expect(masPreflightScript.contains("./scripts/build-mas-app.sh"))
        #expect(masPreflightScript.contains("./scripts/verify-mas-build.sh --require-apple-distribution"))
        #expect(masPreflightScript.contains("./scripts/package-mas-pkg.sh"))
        #expect(masPreflightScript.contains("Manual gates still required before App Store upload"))
        #expect(masPreflightScript.contains("./scripts/check-app-store-submission-gates.sh --require-human-gates"))
        #expect(appStoreUploadScript.contains("This script does not upload anything"))
        #expect(appStoreUploadScript.contains("TOKEN_MONITOR_APP_STORE_CONNECT_API_KEY_ID"))
        #expect(appStoreUploadScript.contains("TOKEN_MONITOR_APP_STORE_CONNECT_API_PRIVATE_KEY_PATH"))
        #expect(appStoreUploadScript.contains("TOKEN_MONITOR_APP_STORE_USERNAME"))
        #expect(appStoreUploadScript.contains("TOKEN_MONITOR_APP_STORE_APP_PASSWORD"))
        #expect(appStoreUploadScript.contains("No App Store Connect upload tool is available"))
        #expect(appStoreUploadScript.contains("Mac App Store installer distribution identity"))
        #expect(appStoreUploadScript.contains("App Store upload readiness is strict-clean"))
        #expect(appStoreGateScript.contains("--require-human-gates"))
        #expect(appStoreGateScript.contains("TOKEN_MONITOR_REQUIRE_APP_STORE_HUMAN_GATES"))
        #expect(appStoreGateScript.contains("TOKEN_MONITOR_APP_STORE_ACCOUNT_HOLDER_APPROVED"))
        #expect(appStoreGateScript.contains("TOKEN_MONITOR_APP_STORE_CONNECT_READY"))
        #expect(appStoreGateScript.contains("TOKEN_MONITOR_APP_STORE_PRIVACY_APPROVED"))
        #expect(appStoreGateScript.contains("TOKEN_MONITOR_APP_STORE_REVIEWER_PLAN_APPROVED"))
        #expect(appStoreGateScript.contains("TOKEN_MONITOR_APP_STORE_SCREENSHOTS_APPROVED"))
        #expect(appStoreGateScript.contains("TOKEN_MONITOR_APP_STORE_SUPPORT_URL_APPROVED"))
        #expect(appStoreGateScript.contains("TOKEN_MONITOR_APP_STORE_SANDBOX_SMOKE_TEST_PASSED"))
        #expect(appStoreGateScript.contains("Mac App Store human gates are incomplete"))
        #expect(appStoreGateScript.contains("Run ./scripts/preflight-mas-submission.sh for the technical MAS build gate."))
        #expect(publicationLegalGateScript.contains("TOKEN_MONITOR_LICENSE_DECISION_APPROVED"))
        #expect(publicationLegalGateScript.contains("TOKEN_MONITOR_PUBLIC_CLAIMS_APPROVED"))
        #expect(publicationLegalGateScript.contains("TOKEN_MONITOR_SUPPORT_SECURITY_APPROVED"))
        #expect(publicationLegalGateScript.contains("TOKEN_MONITOR_PRIVACY_POLICY_APPROVED"))
        #expect(publicationLegalGateScript.contains("No repository license file exists"))
        #expect(publicationLegalGateScript.contains("Publication/legal gates are incomplete"))
        #expect(preflightScript.contains("./scripts/check-github-release-secrets.sh"))
        #expect(preflightScript.contains("./scripts/check-github-release-secrets.sh --require-signing-secrets"))
        #expect(preflightScript.contains("./scripts/check-apple-distribution.sh"))
        #expect(preflightScript.contains("--require-distribution-ready"))
        #expect(preflightScript.contains("./scripts/check-apple-distribution.sh --require-ready"))
        #expect(masReadinessScript.contains("Mac App Store readiness"))
        #expect(masReadinessScript.contains("TOKEN_MONITOR_MAS_BUILD"))
        #expect(masReadinessScript.contains("LSApplicationCategoryType"))
        #expect(masReadinessScript.contains("Info.plist declares an App Store category"))
        #expect(masReadinessScript.contains("MAS build script exists: scripts/build-mas-app.sh"))
        #expect(masReadinessScript.contains("SMAppService login items"))
        #expect(masReadinessScript.contains("Mac App Store static readiness has blockers"))
        #expect(masReadinessScript.contains("exit 1"))
        #expect(masReadinessScript.contains("Mac App Store static readiness has no blockers"))
        #expect(credentialRunbook.contains("Do not share Apple ID passwords"))
        #expect(credentialRunbook.contains("base64 -i /path/to/DeveloperIDApplication.p12"))
        #expect(credentialRunbook.contains("TOKEN_MONITOR_DEVELOPER_ID_CERTIFICATE_BASE64"))
        #expect(credentialRunbook.contains("TOKEN_MONITOR_NOTARY_APP_PASSWORD"))
        #expect(credentialRunbook.contains("SPARKLE_PRIVATE_KEY"))
        #expect(credentialRunbook.contains("After Credentials Are Ready"))
        #expect(credentialRunbook.contains("./scripts/preflight-release.sh --require-signing-secrets"))
        #expect(credentialRunbook.contains("./scripts/audit-apple-distribution.sh --require-complete --run-tests"))
        #expect(credentialRunbook.contains("./scripts/package-release.sh --require-distribution-ready"))
        #expect(credentialRunbook.contains("./scripts/check-apple-distribution.sh --require-ready"))
        #expect(credentialRunbook.contains("TOKEN_MONITOR_VERIFY_DMG_SIGNATURE=1"))
        #expect(credentialRunbook.contains("Release` workflow manually with the existing tag"))
        #expect(credentialRunbook.contains("xcrun notarytool store-credentials token-monitor-notary"))
        #expect(credentialRunbook.contains("Mac App Store Certificates"))
        #expect(credentialRunbook.contains("App Store Connect Upload Credentials"))
        #expect(credentialRunbook.contains("TOKEN_MONITOR_MAS_INSTALLER_IDENTITY"))
        #expect(credentialRunbook.contains("TOKEN_MONITOR_APP_STORE_CONNECT_API_KEY_ID"))
        #expect(credentialRunbook.contains("dist/mas/TokenMonitor-macOS-AppStore.pkg"))
        #expect(masFeasibility.contains("Mac App Store distribution is not ready as-is."))
        #expect(masFeasibility.contains("./scripts/check-mas-readiness.sh"))
        #expect(masFeasibility.contains("scripts/check-app-store-identity.sh --require-ready"))
        #expect(masFeasibility.contains("scripts/package-mas-pkg.sh"))
        #expect(masFeasibility.contains("scripts/check-app-store-upload-readiness.sh"))
        #expect(masFeasibility.contains("Verify Sparkle is absent from the MAS binary."))
        #expect(masFeasibility.contains("com.apple.security.app-sandbox"))
        #expect(masFeasibility.contains("packaging/TokenMonitorMAS.entitlements"))
        #expect(masFeasibility.contains("WKWebsiteDataStore.default()"))
        #expect(masFeasibility.contains("SMAppService.mainApp"))
        #expect(masFeasibility.contains("scripts/build-mas-app.sh"))
        #expect(masEntitlements.contains("com.apple.security.app-sandbox"))
        #expect(masEntitlements.contains("com.apple.security.network.client"))
        #expect(appStoreIdentity.contains("App Store Connect Identity Checklist"))
        #expect(appStoreIdentity.contains("./scripts/check-app-store-identity.sh --require-ready"))
        #expect(appStoreIdentity.contains("com.mediapublishing.tokenmonitor"))
        #expect(appStoreIdentity.contains("public.app-category.productivity"))
        #expect(appStoreIdentity.contains("TOKEN_MONITOR_APP_STORE_SKU"))
        #expect(appStoreIdentity.contains("Values required by the strict checker"))
        #expect(appStoreIdentity.contains("TOKEN_MONITOR_APP_STORE_CATEGORY_APPROVED=1"))
        #expect(releaseRecoveryRunbook.contains("Release Recovery Runbook"))
        #expect(releaseRecoveryRunbook.contains("Hotfix Release"))
        #expect(releaseRecoveryRunbook.contains("Appcast Rollback"))
        #expect(releaseRecoveryRunbook.contains("Mac App Store Recovery"))
        #expect(releaseRecoveryRunbook.contains("Credential Exposure"))
        #expect(releaseRecoveryRunbook.contains("GitHub Issues are public"))
        #expect(releaseRecoveryRunbook.contains("SPARKLE_PRIVATE_KEY"))
        #expect(releaseRecoveryScript.contains("workflow_dispatch:"))
        #expect(releaseRecoveryScript.contains("TOKEN_MONITOR_VERIFY_DMG_SIGNATURE=1"))
        #expect(releaseRecoveryScript.contains("docs/release-recovery-runbook.md"))
        #expect(legalChecklist.contains("No repository license is published yet."))
        #expect(legalChecklist.contains("Do not choose a software license on behalf of the owner."))
        #expect(legalChecklist.contains("./scripts/check-publication-legal-gates.sh --require-legal-gates"))
        #expect(legalChecklist.contains("docs/app-store-privacy-labels.md"))
        #expect(legalChecklist.contains("docs/privacy.md"))
        #expect(legalChecklist.contains("SECURITY.md"))
        #expect(appStorePacket.contains("Reviewer Notes Draft"))
        #expect(appStorePacket.contains("Reviewer Test Plan"))
        #expect(appStorePacket.contains("docs/app-store-connect-identity.md"))
        #expect(appStorePacket.contains("./scripts/check-app-store-identity.sh --require-ready"))
        #expect(appStorePacket.contains("com.mediapublishing.tokenmonitor"))
        #expect(appStorePacket.contains("Privacy Label Draft"))
        #expect(appStorePacket.contains("./scripts/check-app-store-metadata.sh"))
        #expect(appStorePacket.contains("./scripts/check-app-store-screenshots.sh --require-ready"))
        #expect(appStorePacket.contains("AI tools"))
        #expect(appStorePacket.contains("docs/app-store-privacy-labels.md"))
        #expect(appStorePacket.contains("docs/app-store-screenshot-checklist.md"))
        #expect(appStorePacket.contains("2880 x 1800"))
        #expect(appStorePacket.contains("scripts/verify-mas-build.sh"))
        #expect(appStorePacket.contains("--require-apple-distribution"))
        #expect(appStorePacket.contains("scripts/package-mas-pkg.sh"))
        #expect(appStorePacket.contains("scripts/check-app-store-upload-readiness.sh"))
        #expect(appStorePacket.contains("TOKEN_MONITOR_MAS_INSTALLER_IDENTITY"))
        #expect(appStorePacket.contains("TokenMonitor-macOS-AppStore.pkg"))
        #expect(appStorePacket.contains("./scripts/preflight-mas-submission.sh"))
        #expect(appStorePacket.contains("./scripts/check-app-store-identity.sh --require-ready"))
        #expect(appStorePacket.contains("The preflight runs:"))
        #expect(appStorePacket.contains("docs/mas-sandbox-smoke-test.md"))
        #expect(appStorePacket.contains("TOKEN_MONITOR_MAS_CODESIGN_IDENTITY"))
        #expect(appStorePacket.contains("scripts/check-app-store-submission-gates.sh --require-human-gates"))
        #expect(appStorePacket.contains("TOKEN_MONITOR_APP_STORE_ACCOUNT_HOLDER_APPROVED"))
        #expect(appStorePacket.contains("Do not use personal accounts."))
        #expect(appStorePacket.contains("No Sparkle framework or `SU*` Info.plist keys"))
        #expect(appStorePrivacyLabels.contains("No, Token Monitor does not collect data from this app."))
        #expect(appStorePrivacyLabels.contains("No, Token Monitor does not track users across apps or websites."))
        #expect(appStorePrivacyLabels.contains("TOKEN_MONITOR_APP_STORE_PRIVACY_APPROVED=1"))
        #expect(appStorePrivacyLabels.contains("Debug mode still opens drafts only"))
        #expect(appStorePrivacyLabels.contains("Apple App Privacy Details"))
        #expect(appStoreScreenshotChecklist.contains("1 to 10 screenshots"))
        #expect(appStoreScreenshotChecklist.contains("16:10 aspect ratio"))
        #expect(appStoreScreenshotChecklist.contains("1280 x 800"))
        #expect(appStoreScreenshotChecklist.contains("2880 x 1800"))
        #expect(appStoreScreenshotChecklist.contains("dist/app-store/screenshots/"))
        #expect(appStoreScreenshotChecklist.contains("./scripts/check-app-store-screenshots.sh --require-ready"))
        #expect(appStoreScreenshotChecklist.contains("TOKEN_MONITOR_APP_STORE_SCREENSHOTS_APPROVED=1"))
        #expect(appStoreScreenshotChecklist.contains("Do not commit App Store screenshots"))
        #expect(masSmokeTest.contains("Pass Criteria"))
        #expect(masSmokeTest.contains("Fail Conditions"))
        #expect(masSmokeTest.contains("docs/mas-sandbox-smoke-test-receipt.md"))
        #expect(masSmokeTest.contains("Launch at Login"))
        #expect(masSmokeTest.contains("Debug GitHub draft"))
        #expect(masSmokeTest.contains("Debug email draft"))
        #expect(masSmokeTest.contains("Approved by Account Holder"))
        #expect(masSmokeTestReceipt.contains("Required Command Evidence"))
        #expect(masSmokeTestReceipt.contains("Privacy Review"))
        #expect(masSmokeTestReceipt.contains("./scripts/verify-mas-build.sh --require-apple-distribution"))
        #expect(masSmokeTestReceipt.contains("./scripts/check-app-store-upload-readiness.sh --require-ready"))
        #expect(masSmokeTestReceipt.contains("Screenshots contain no cookies, tokens, or debug dumps"))
        #expect(masSmokeTestReceipt.contains("Approved by Account Holder"))
    }

    @Test func publicIssueTemplatesProtectPrivateDebugData() throws {
        let rootURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()

        let distributionDoc = try String(
            contentsOf: rootURL.appendingPathComponent("docs/apple-distribution-readiness.md"),
            encoding: .utf8
        )
        let parserIssueTemplateURL = rootURL.appendingPathComponent(".github/ISSUE_TEMPLATE/parser-layout-bug.yml")
        let installIssueTemplateURL = rootURL.appendingPathComponent(".github/ISSUE_TEMPLATE/install-update-bug.yml")
        let issueConfigURL = rootURL.appendingPathComponent(".github/ISSUE_TEMPLATE/config.yml")
        let parserIssueTemplate = try String(contentsOf: parserIssueTemplateURL, encoding: .utf8)
        let installIssueTemplate = try String(contentsOf: installIssueTemplateURL, encoding: .utf8)
        let issueConfig = try String(contentsOf: issueConfigURL, encoding: .utf8)

        #expect(FileManager.default.fileExists(atPath: parserIssueTemplateURL.path))
        #expect(FileManager.default.fileExists(atPath: installIssueTemplateURL.path))
        #expect(FileManager.default.fileExists(atPath: issueConfigURL.path))
        #expect(distributionDoc.contains(".github/ISSUE_TEMPLATE/parser-layout-bug.yml"))
        #expect(distributionDoc.contains(".github/ISSUE_TEMPLATE/install-update-bug.yml"))
        #expect(parserIssueTemplate.contains("GitHub Issues are public"))
        #expect(parserIssueTemplate.contains("Do not attach raw debug dumps"))
        #expect(parserIssueTemplate.contains("chat titles"))
        #expect(parserIssueTemplate.contains("usage budgets"))
        #expect(parserIssueTemplate.contains("Token Monitor version"))
        #expect(parserIssueTemplate.contains("Account language or locale"))
        #expect(parserIssueTemplate.contains("Privacy check"))
        #expect(installIssueTemplate.contains("GitHub Issues are public"))
        #expect(installIssueTemplate.contains("Apple ID passwords"))
        #expect(installIssueTemplate.contains("GitHub Secrets"))
        #expect(installIssueTemplate.contains("Gatekeeper"))
        #expect(installIssueTemplate.contains("Sparkle update"))
        #expect(installIssueTemplate.contains("Launch at Login"))
        #expect(installIssueTemplate.contains("Privacy check"))
        #expect(issueConfig.contains("blank_issues_enabled: false"))
        #expect(!parserIssueTemplate.contains("info@etraininghq.com"))
        #expect(!installIssueTemplate.contains("info@etraininghq.com"))
        #expect(!issueConfig.contains("info@etraininghq.com"))
    }

    @Test func supportPageRoutesPublicAndPrivateReports() throws {
        let rootURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()

        let readme = try String(
            contentsOf: rootURL.appendingPathComponent("README.md"),
            encoding: .utf8
        )
        let launchKit = try String(
            contentsOf: rootURL.appendingPathComponent("docs/marketing-launch-kit.md"),
            encoding: .utf8
        )
        let supportURL = rootURL.appendingPathComponent("SUPPORT.md")
        let support = try String(contentsOf: supportURL, encoding: .utf8)
        let securityURL = rootURL.appendingPathComponent("SECURITY.md")
        let security = try String(contentsOf: securityURL, encoding: .utf8)

        #expect(FileManager.default.fileExists(atPath: supportURL.path))
        #expect(FileManager.default.fileExists(atPath: securityURL.path))
        #expect(readme.contains("SUPPORT.md"))
        #expect(readme.contains("SECURITY.md"))
        #expect(launchKit.contains("https://github.com/MediaPublishing/token-monitor/blob/main/SUPPORT.md"))
        #expect(support.contains("GitHub Issues are public"))
        #expect(support.contains("Do not post raw debug dumps"))
        #expect(support.contains("Installation Or Gatekeeper"))
        #expect(support.contains("install-update-bug.yml"))
        #expect(support.contains("parser-layout-bug.yml"))
        #expect(support.contains("docs/privacy.md"))
        #expect(support.contains("SECURITY.md"))
        #expect(support.contains("Apple ID passwords"))
        #expect(!support.contains("info@etraininghq.com"))
        #expect(security.contains("Reporting A Vulnerability"))
        #expect(security.contains("Do not open a public issue"))
        #expect(security.contains("GitHub private vulnerability reporting"))
        #expect(security.contains("Developer ID `.p12` files or passwords"))
        #expect(security.contains("docs/privacy.md"))
        #expect(!security.contains("info@etraininghq.com"))
    }

    @Test func marketingLaunchKitCoversDistributionMetadata() throws {
        let rootURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()

        let readme = try String(
            contentsOf: rootURL.appendingPathComponent("README.md"),
            encoding: .utf8
        )
        let landingHTML = try String(
            contentsOf: rootURL.appendingPathComponent("landing/index.html"),
            encoding: .utf8
        )
        let distributionDoc = try String(
            contentsOf: rootURL.appendingPathComponent("docs/apple-distribution-readiness.md"),
            encoding: .utf8
        )
        let launchKitURL = rootURL.appendingPathComponent("docs/marketing-launch-kit.md")
        let launchKit = try String(contentsOf: launchKitURL, encoding: .utf8)
        let privacyURL = rootURL.appendingPathComponent("docs/privacy.md")
        let privacy = try String(contentsOf: privacyURL, encoding: .utf8)

        #expect(FileManager.default.fileExists(atPath: launchKitURL.path))
        #expect(FileManager.default.fileExists(atPath: privacyURL.path))
        #expect(readme.contains("docs/marketing-launch-kit.md"))
        #expect(readme.contains("docs/privacy.md"))
        #expect(landingHTML.contains("docs/privacy.md"))
        #expect(distributionDoc.contains("docs/marketing-launch-kit.md"))
        #expect(launchKit.contains("Direct Distribution Listing"))
        #expect(launchKit.contains("Mac App Store Draft Metadata"))
        #expect(launchKit.contains("Privacy label draft"))
        #expect(launchKit.contains("https://github.com/MediaPublishing/token-monitor/blob/main/docs/privacy.md"))
        #expect(launchKit.contains("Review notes draft"))
        #expect(launchKit.contains("Screenshot Inventory"))
        #expect(launchKit.contains("docs/app-store-screenshot-checklist.md"))
        #expect(launchKit.contains("Launch Checklist"))
        #expect(launchKit.contains("./scripts/check-github-release-secrets.sh --require-signing-secrets"))
        #expect(launchKit.contains("./scripts/preflight-release.sh --require-signing-secrets"))
        #expect(launchKit.contains("./scripts/package-release.sh --require-distribution-ready"))
        #expect(launchKit.contains("./scripts/package-mas-pkg.sh"))
        #expect(launchKit.contains("./scripts/check-app-store-metadata.sh"))
        #expect(launchKit.contains("./scripts/check-app-store-screenshots.sh --require-ready"))
        #expect(launchKit.contains("./scripts/check-app-store-identity.sh --require-ready"))
        #expect(launchKit.contains("./scripts/check-app-store-upload-readiness.sh --require-ready"))
        #expect(launchKit.contains("./scripts/check-app-store-submission-gates.sh --require-human-gates"))
        #expect(launchKit.contains("./scripts/check-publication-legal-gates.sh --require-legal-gates"))
        #expect(launchKit.contains("./scripts/check-release-recovery-readiness.sh --require-ready"))
        #expect(launchKit.contains("Gatekeeper, stapler, GitHub release ZIP, and Sparkle update ZIP checks"))
        #expect(launchKit.contains("./scripts/verify-public-release.sh <tag> <version> <build>"))
        #expect(launchKit.contains("TOKEN_MONITOR_VERIFY_DMG_SIGNATURE=1"))
        #expect(launchKit.contains("published DMG, GitHub release ZIP, and Sparkle update ZIP"))
        #expect(launchKit.contains("Approval Gates"))
        #expect(launchKit.contains("License choice and formal publication/legal approval."))
        #expect(launchKit.contains("https://mediapublishing.github.io/token-monitor/"))
        #expect(launchKit.contains("https://github.com/MediaPublishing/token-monitor/blob/main/SUPPORT.md"))
        #expect(launchKit.contains("Token Monitor is not affiliated with Anthropic, OpenAI, or Apple."))
        #expect(privacy.contains("does not send usage data to Token Monitor server infrastructure"))
        #expect(privacy.contains("Provider login sessions managed by WebKit"))
        #expect(privacy.contains("Debug mode is off by default"))
        #expect(privacy.contains("GitHub Issues are public"))
        #expect(privacy.contains("docs/app-store-privacy-labels.md"))
    }
}
